### ISSUE TITLE
ktFOCUSS2DT.m line 133:  d  may be modified to d_old ?

### ISSUE THREAD

**Issue by siatjiasen** [thomaskuestner/CS_MoCo_LAB#1]
Hi, 

Thank you for sharing CS_LAB. 

I tried MATLAB version for 2DT recon, and encountered an error about missing 'd_old'. Maybe the 'd' variable @ line 133 in ktFOCUSS2DT.m should be changed to 'd_old'.

Moreover, is it possible to recompiled the CS_LAB_Gadget library for Gadgetron on Linux (ubuntu 14.04 LTS) , that is changing from .dll/.lib file to .so file)? Would you please to show me how much CS_LAB_Gadget (C++) is open sourced ? We are working on implementing an improved 2DT recon (k-t ISD) based on k-t FOCUSS, and wish to start from CS_LAB_Gadget if possible. 

Thank you again.
Best wishes,
Jia Sen

**Comment by thomaskuestner** [comment]
Hi Jia Sen,

thanks for pointing this out. I corrected the matlab version of the 2Dt FOCUSS.
The initialization of the variable 'd_old' (storing previous iteration gradient direction) was missing.

All Gadgetron related files are open source and included in this repository. You find the FOCUSS Gadgetron implementation under c++\src\FOCUSS. You may recompile CS_LAB_Gadget for your targeted machine following the "CMakeLists.txt".

Kind regards
Thomas
