### ISSUE TITLE
CS_LAB library not found by Gadgetron with RegistrationGadget

### ISSUE THREAD

**Issue by F462** [thomaskuestner/CS_MoCo_LAB#17]
When the CS_LAB is compiled with RegistrationGadget (CMakeLists.txt lines 339 & 374), Gadgetron is not able to find the library. Commenting these lines out solves the problem (but cannot be the fix, obviously). See also commit 3c313aec.

**Comment by thomaskuestner** [comment]
Potential name conflict with Gadgetron base registration tool
I pushed a renamed version into WIP https://github.com/thomaskuestner/CS_MoCo_LAB/commit/236a6b343f166179bfa19209c261711f520538cc
@F462 Please check if this solves the linker error (I don't have a Gadgetron system set up at the moment)

**Comment by F462** [comment]
Great idea, but unfortunately the error persists.

**Comment by F462** [comment]
Solution found:
RegistrationGadget.h (now ElastixRegistrationGadget.h) includes elastixlib.h.
When CS_LAB is compiled without the presence of elastix as shared library (be aware: this is the default if you compile and install elastix without any changes!) the resulting library cannot be used by Gadgetron.
See commit 0d0d2f5, CMakeLists.txt and the docker build environment for more information.
