### ISSUE TITLE
CMakeLists.txt for compiling 'subsampling.exe' on ubuntu 14.04

### ISSUE THREAD

**Issue by siatjiasen** [thomaskuestner/CS_MoCo_LAB#2]
# ---------------------------
# The code for 'subsampling.exe' can be compiled easily.
# This CMakeLists.txt is provided just for easier on Ubuntu 14.04.

project(subsampling)

cmake_minimum_required(VERSION 2.8)

set(include_file Approx.h LinkedList.h Point.h SomeFunctions.h VariableDensity.h VDSamplingUpper.h SubsampleMain.h)
set(src_file Approx.cpp LinkedList.cpp Point.cpp SomeFunctions.cpp VariableDensity.cpp VDSamplingUpper.cpp SubsampleMain.cpp)
set(CMAKE_INSTALL_PATH ${CMAKE_HOME_DIRECTORY})

add_executable(subsampling ${src_file} ${include_file})

install(TARGETS subsampling RUNTIME DESTINATION ${CMAKE_INSTALL_PATH})

**Comment by thomaskuestner** [comment]
Thanks for sharing this!
I included it in the repository.
