### ISSUE TITLE
no fCreateLoopImages in repository

### ISSUE THREAD

**Issue by schrau24** [thomaskuestner/CS_MoCo_LAB#38]
This function is called twice in ktFOCUSS4DMotion.m (lines 147 and 279), but it does not seem to exist anywhere in the repository. Can you please upload this file?

**Comment by thomaskuestner** [comment]
This function is only used for plotting the flow fields. I have commented out the lines in the code and added the function to the repo in case you wanna use it: https://github.com/thomaskuestner/CS_MoCo_LAB/commit/ee9b8b2cfc1947a20e82e20ee3944dc65f2d913a

**Comment by schrau24** [comment]
Thanks for the quick reply - nice repository!
